# Generated by Django 4.2.17 on 2025-01-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterField(
            model_name='task',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_task_name_per_author'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasker.task'),
        ),
    ]
