# Generated by Django 4.2.17 on 2025-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_subtask_alter_task_options_alter_task_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('slug', 'author'), name='unique_task_slug_per_author'),
        ),
    ]
