from django.db import models
from django.db.models.query import QuerySet
from django.utils.text import slugify
from django.contrib.auth.models import User


class Task(models.Model):
    '''
    Stores a single task entry related to :model:`auth.User`.
    
    **Fields:**
    
    ``name``
        The name of the task.
    ``slug``
        A unique slug for the task.
    ``author``
        The author of the task.
    ``is_completed``
        A boolean indicating if the task is completed.
    ``date_updated``
        The date and time the task was last updated.
    ``likes``
        The number of likes the task has received.
    ``subtasks``
        QuerySet of :model:`tasker.Subtask` objects related to the task.
    
    **Constraints:**
    
    - Prevent multiple tasks with the same name from the same author.
    - Prevent multiple tasks with the same slug from the same author.
        
    **Methods:**
    
    ``save``
        Overriding the save method to automatically generate a slug for the task.
    ``__str__``
        String representation of the model.
    '''
    
    name = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200, unique=False, blank=True, editable=False)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='tasker_tasks')
    is_completed = models.BooleanField(default=False)
    date_updated = models.DateTimeField(auto_now=True)
    likes = models.PositiveIntegerField(default=0)

    # Tell linter that `subtasks` is a QuerySet of Subtask objects
    subtasks: QuerySet["Subtask"]  

    def save(self, *args, **kwargs):
        '''
        Overriding the save method to automatically generate a slug for the task.
        
        The slug is generated by converting the task name to a slug and appending 
        a number to the slug if a task with the same slug already exists.
        '''
        
        current_slug = slugify(self.name)
        unique_slug = current_slug
        num = 1
        
        # Check if a task with the same slug already exists, excluding the current task.
        # If it does, append a number to the slug to make it unique.
        while (
            Task.objects.filter(slug=unique_slug, author=self.author)
            .exclude(pk=self.pk)
            .exists()
            ):
            unique_slug = f"{current_slug}-{num}"
            num += 1
        
        self.slug = unique_slug
        super().save(*args, **kwargs)
    
    class Meta:
        # Unique constraints to prevent:
        # - Multiple tasks with the same name from the same author.
        # - Multiple tasks with the same slug from the same author.
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'author'], name='unique_task_name_per_author'),
            models.UniqueConstraint(
                fields=['slug', 'author'], name='unique_task_slug_per_author')
        ]
        ordering = ['-date_updated']
    
    def __str__(self):
        '''
        String representation of Task model.
        '''
        
        return f"TASK: {self.name} | {self.author}"


class Subtask(models.Model):
    '''
    Stores a single subtask entry related to :model:`tasker.Task`.
    
    **Fields:**
    
    ``title``
        The title of the subtask.
    ``note``
        Additional notes for the subtask.
    ``task``
        The task the subtask is related to.
    ``is_completed``
        A boolean indicating if the subtask is completed.
        
    **Methods:**
    
    ``__str__``
        String representation of the model.
    '''
    
    title = models.CharField(max_length=200)
    note = models.TextField(blank=True)
    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name='subtasks')
    is_completed = models.BooleanField(default=False)
    
    # String representation of Subtask model.
    def __str__(self):
        return f"SUBTASK: {self.title} | {self.task}"